{
 "title": "Agent Details",
 "time": { "from": "now/d", "to": "now/d" },
 "templating": {
  "list": [
   {
    "name": "agent",
    "label": "Agent",
    "query": "select name from users where role= 'agent';"
   }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Motion Bull Campaigns",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT \r\n\tb.name as 'Motion Bull Campaign'\r\nFROM \r\n\tuser_has_voice_queues a,\r\n\tvoice_queues b,\r\n\tusers c\r\nWHERE \r\n\tb.`type` = 'outbound'\r\n\tAND a.UserId = c.id\r\n\tAND a.VoiceQueueId = b.id\r\n\tAND c.name = '$agent'"
      }
     ]
    },
    {
     "title": "Voice Queues",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 4, "x": 3, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT \r\n\tb.name as 'Voice Queue'\r\nFROM \r\n\tuser_has_voice_queues a,\r\n\tvoice_queues b,\r\n\tusers c\r\nWHERE \r\n\tb.`type` = 'inbound'\r\n\tAND a.UserId = c.id\r\n\tAND a.VoiceQueueId = b.id\r\n\tAND c.name = '$agent'"
      }
     ]
    },
    {
     "title": "Queues and Campaigns",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 6, "w": 5, "x": 7, "y": 1 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "SELECT\r\n  now() as time,\r\n\tCASE \r\n\t\tWHEN TYPE='outbound' THEN 'Dialer Campaign'\r\n\t\tWHEN TYPE='inbound' THEN 'Vocie Queue'\r\n\tEND AS QueueType,\r\n\tCOUNT(1) AS 'value'\r\nFROM \r\n\tvoice_queues\r\nWHERE \r\n\tid in\r\n\t(\r\n\t\tSELECT voicequeueid FROM user_has_voice_queues WHERE userid= (SELECT id FROM users WHERE NAME='$agent')\r\n\t)\r\nGROUP BY QueueType"
      }
     ]
    },
    {
     "title": "Summary",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT \r\n\tid AS 'User id',\r\n\t`name` AS login,\r\n\tfullname AS 'User name',\r\n\temail AS 'E-mail',\r\n\tinternal AS 'PBX Extension',\r\n\tonline as 'Logged'\r\nFROM \r\n  users\r\nWHERE \r\n  `name`='$agent'\r\n"
      }
     ]
    }
   ]
  },
  { "title": "Calls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Llamadas Totales",
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \n\tCOUNT(a.id) as 'Total Calls'\nFROM \n\treport_call a,\n\tusers b\nWHERE\n\tb.name='$agent' \n\tAND a.userId = b.id\n\tAND $__timeFilter(starttime)\nORDER BY\n  a.type ASC;\n"
    }
   ]
  },
  {
   "title": "Outgoing Agent Calls",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 7, "x": 3, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT \n\tCOUNT(a.id) as 'Total Calls',\n\ta.type as 'Call type',\n\ta.disposition as 'Result'\nFROM \n\treport_call a,\n\tusers b\nWHERE\n\tb.name='$agent' \n\tAND a.userId = b.id\n\tAND $__timeFilter(starttime)\nGROUP BY \n\ta.type,a.disposition\nORDER BY\n  a.type ASC;\n"
    }
   ]
  },
  {
   "title": "Outgoing Calls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \r\n\t$__timeGroup(a.starttime,'1h') as time,\r\n\tCOUNT(a.id) AS 'value',\r\n\tCASE \r\n\t\tWHEN a.type='dialer' AND a.disposition='ANSWERED' THEN \"Dialer Answer\"\r\n\t\tWHEN a.type='dialer' AND a.disposition='NO ANSWER' THEN \"Dialer No Answer\"\r\n\t\tWHEN a.type='outbound' AND a.disposition='ANSWERED' THEN \"Manual Answer\"\r\n\t\tWHEN a.type='outbound' AND a.disposition='NO ANSWER' THEN \"Manual No Answer\"\r\n\tEND as metric\t\r\nFROM \r\n\treport_call a,\r\n\tusers b\r\nWHERE\r\n\tb.name='$agent' \r\n\tAND a.userId = b.id\r\nGROUP BY \r\n\ttime,metric\r\nORDER BY $__timeGroup(starttime,'1h') ASC\r\n"
    }
   ]
  },
  {
   "title": "Manual Calls",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \r\n\t$__timeGroup(starttime,'1h') as time,\r\n\tCOUNT(a.id) AS value,\r\n\ta.disposition as metric\r\nFROM \r\n\treport_call a,\r\n\tusers b\r\nWHERE\r\n\tb.name='$agent'\r\n\tAND \r\n\ta.userId = b.id\r\n\tAND a.type='outbound'\r\nGROUP BY \r\n\ttime, metric\r\nORDER BY $__timeGroup(starttime,'1h') ASC"
    }
   ]
  },
  {
   "title": "Dialer Calls",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \r\n\t$__timeGroup(starttime,'1h') as time,\r\n\tCOUNT(a.id) AS value,\r\n\ta.disposition as metric\r\nFROM \r\n\treport_call a,\r\n\tusers b\r\nWHERE\r\n\tb.name='$agent' \r\n\tAND \r\n\ta.userId = b.id\r\n\tAND a.type='dialer'\r\nGROUP BY \r\n\ttime, metric\r\nORDER BY $__timeGroup(starttime,'1h') ASC"
    }
   ]
  },
  {
   "title": "Interval Calls Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interval calls details",
     "type": "table-old",
     "gridPos": { "h": 10, "w": 18, "x": 0, "y": 16 },
     "targets": [
      {
       "rawSql": "SELECT \r\n\tid AS 'Id',\r\n\tTYPE as 'Type',\r\n\tdestination AS 'Destination',\r\n\tcallerid AS  'Contact',\r\n\tduration AS 'Duration',\r\n\tdisposition AS 'State',\r\n\tuserdisposition AS 'Disposition',\r\n\tcreatedAt AS 'Date',\r\n\tcontactId AS 'Contact Id' \r\nFROM \r\n  report_call \r\nWHERE \r\n  userid=(select id from users where name='$agent')\r\n  and $__timeFilter(starttime)\r\n\t"
      }
     ]
    },
    {
     "title": "Interval Calls Type",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 16 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "SELECT \r\n\tNOW() AS time_sec,\r\n\tTYPE AS metric,\r\n\tCOUNT(TYPE) AS value\r\nFROM \r\n  report_call \r\nWHERE \r\n  userid=(select id from users where name='$agent')\r\n  and $__timeFilter(starttime)\r\nGROUP BY metric;"
      }
     ]
    }
   ]
  },
  {
   "title": "Sales and Dispositions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dialer Positive Dispositions",
     "type": "farski-blendstat-panel",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "rawSql": "SELECT\r\n  $__timeGroup(starttime,'30m') as time,\r\n  count(id)\r\nFROM cm_hopper_final\r\nWHERE\r\n   LCASE(disposition) = 'acepta contrato'\r\n   and $__timeFilter(starttime)\r\n   and membername='$agent'\r\nGROUP BY $__timeGroup(starttime,'30m')\r\nORDER BY $__timeGroup(starttime,'30m') ASC"
      }
     ]
    },
    {
     "title": "Dialer Total Dispositions",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 7, "x": 4, "y": 10 },
     "format": "short",
     "valueName": "total",
     "targets": [
      {
       "rawSql": "SELECT\n  now() AS \"time\",\n  disposition as metric,\n  count(disposition) as value\nFROM cm_hopper_final\nWHERE\n  \tmembername = '$agent'\n  and\n    disposition IS NOT NULL\n  and\n\t  $__timeFilter(createdAt)\ngroup by disposition;"
      }
     ]
    },
    {
     "title": "Inbound Positive Dispositions",
     "type": "farski-blendstat-panel",
     "gridPos": { "h": 8, "w": 5, "x": 11, "y": 10 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "rawSql": "SELECT\r\n  $__timeGroup(starttime,'30m') as time,\r\n  count(id)\r\nFROM report_call\r\nWHERE\r\n   LCASE(disposition) = 'ok, cerrado'\r\n   and $__timeFilter(starttime)\r\n   and userid=(select id from users where name='$agent')\r\n   and type='inbound'\r\nGROUP BY $__timeGroup(starttime,'30m')\r\nORDER BY $__timeGroup(starttime,'30m') ASC"
      }
     ]
    },
    {
     "title": "Total Inbound Dispositions",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "SELECT\r\n  now() as 'time_sec',\r\n\tuserdisposition as 'metric',\r\n\tCOUNT(userdisposition) AS 'value'\r\nFROM \r\n\treport_call \r\nWHERE \r\n\tuserid=(SELECT id FROM users WHERE NAME='$agent')\r\n\tAND userdisposition IS NOT null\r\n\tAND TYPE='inbound'\r\nGROUP BY\r\n\tuserdisposition"
      }
     ]
    },
    {
     "title": "Dialer Scheduled Calls",
     "type": "farski-blendstat-panel",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "rawSql": "SELECT\r\n  $__timeGroup(starttime,'30m') as time,\r\n  count(id) as value\r\nFROM cm_hopper_final\r\nWHERE\r\n   membername='$agent'\r\n   and LCASE(disposition) = 'reschedule'\r\n   and $__timeFilter(starttime)\r\nGROUP BY $__timeGroup(starttime,'30m')\r\nORDER BY $__timeGroup(starttime,'30m') ASC"
      }
     ]
    }
   ]
  },
  {
   "title": "States",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Agent Pauses",
     "type": "table-old",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 18 },
     "targets": [
      {
       "rawSql": "SELECT \n\tt1.data1 as 'Pause',\n\tSEC_TO_TIME(sum(duration)) AS \"Total\"\nFROM \n\treport_member t1\nWHERE\n $__timeFilter(createdAt)\n AND t1.CHANNEL='voice'\n AND membername = '$agent'\n and type in ('PAUSE')\n AND lcase(data1) IN\n (\n \t\tSELECT LCASE(name) FROM tools_pauses\n )\nGROUP BY \n\tt1.type,t1.data1\n\n"
      }
     ]
    },
    {
     "title": "Login Info",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 7, "x": 6, "y": 18 },
     "targets": [
      {
       "rawSql": "SELECT \n\tenterAt,exitAt,SEC_TO_TIME(SUM(duration)) AS \"Total\" \nFROM \n\treport_member \nWHERE \n\t$__timeFilter(enterAt)\n\tAND CHANNEL='voice'  \n\tAND membername = '$agent'\n\tAND TYPE='LOGIN'\nGROUP BY enterAt,exitAt,duration;\n"
      }
     ]
    },
    {
     "title": "Changes last 15 minutes",
     "type": "table-old",
     "gridPos": { "h": 12, "w": 7, "x": 13, "y": 18 },
     "targets": [
      {
       "rawSql": "SELECT \n  type,duration,enterAt\nFROM \n  report_member \nWHERE \n  channel='voice' \n  AND membername='$agent' \n  AND enterAt >= DATE_SUB(NOW(), INTERVAL 15 MINUTE)"
      }
     ]
    },
    {
     "title": "Last 15 minutes state times",
     "type": "table-old",
     "gridPos": { "h": 12, "w": 4, "x": 20, "y": 18 },
     "targets": [
      {
       "rawSql": "SELECT \r\n\tTYPE AS metric,\r\n\tSUM(duration) AS value\r\nFROM \r\n\treport_member \r\nWHERE \r\n\tCHANNEL='voice' \r\n\tAND membername='$agent' \r\n\tAND enterAt >= DATE_SUB(NOW(), INTERVAL 15 MINUTE) \r\nGROUP BY metric"
      }
     ]
    },
    {
     "title": "Total Time",
     "type": "table-old",
     "description": "Difference between Login state and Pause+Talking are due intermediate states as calling state",
     "gridPos": { "h": 6, "w": 7, "x": 6, "y": 24 },
     "targets": [
      {
       "rawSql": "SELECT \n\ttype as 'State',\n\tSEC_TO_TIME(SUM(duration)) AS \"Total\"\nFROM \n\treport_member\nWHERE\n $__timeFilter(createdAt)\n AND CHANNEL='voice'\n AND membername = '$agent'\nGROUP BY \n\ttype;"
      }
     ]
    }
   ]
  }
 ]
}