{
 "title": "Agents Global",
 "time": { "from": "now/d", "to": "now/d" },
 "panels": [
  {
   "title": "Total logged",
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  now() as 'time_sec',\n  count(id) as 'value'\nFROM \n  users\nWHERE\n  role='agent' and online=1"
    }
   ]
  },
  {
   "title": "Total Agents",
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  now() as 'time_sec',\n  count(id) as 'value'\nFROM \n  users\nWHERE\n  role='agent'"
    }
   ]
  },
  {
   "title": "Total Unavailable",
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 3, "w": 10, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  now() as 'time_sec',\n  count(id) as 'value'\nFROM \n  users\nWHERE\n  role='agent' and online=0"
    }
   ]
  },
  {
   "title": "Logged Agents",
   "type": "table-old",
   "gridPos": { "h": 20, "w": 9, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT \n  id,name,context,\n  case\n    when extensionMonitor != '' then 1\n    else 0\n  end as 'record',\n  loginInPause\nfrom \n  users\nwhere \n  role='agent'\n  and online='1'"
    }
   ]
  },
  {
   "title": "Logged Agents",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\r\n  now() as 'time_sec',\r\n  count(online) as 'value',\r\n  case\r\n  \twhen ONLINE='1' then 'Available'\r\n  \tELSE 'Unavailable'\r\n  END AS metric\r\nFROM \r\n  users\r\nWHERE\r\n  role='agent'\r\nGROUP BY metric"
    }
   ]
  },
  {
   "title": "Unavailable Agents",
   "type": "table-old",
   "gridPos": { "h": 23, "w": 10, "x": 14, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT \n  id,name,context,\n  case\n    when extensionMonitor != '' then 1\n    else 0\n  end as 'record',\n  loginInPause\nfrom \n  users\nwhere \n  role='agent'\n  and online='0'"
    }
   ]
  },
  {
   "title": "Agents with record",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\r\n  now() as 'time_sec',\r\n  count(extensionMonitor) as 'value',\r\n  case \r\n    when extensionMonitor != '' then 'yes' \r\n    else 'no' \r\n  end as 'metric'\r\nFROM \r\n  users\r\nWHERE\r\n  role='agent'\r\nGROUP BY metric"
    }
   ]
  }
 ]
}