{
 "title": "Main Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Users/Agents",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT \r\n  now() as 'time_sec',\r\n\tCOUNT(role) AS 'value',\r\n  role\r\nFROM \r\n\tusers\r\nGROUP BY\r\n\trole,time_sec\r\n"
    }
   ]
  },
  {
   "title": "Logged Agents",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 6, "x": 5, "y": 1 },
   "targets": [
    {
     "rawSql": "select name as 'Name' from users where useragent != ''"
    }
   ]
  },
  {
   "title": "Motion Bull Campaings",
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 2, "w": 4, "x": 11, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \n  now() as 'time_sec',\n  COUNT(id) as 'value'\nFROM\n voice_queues \nWHERE \n  type='Outbound'"
    }
   ]
  },
  {
   "title": "IVR Campaings",
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 2, "w": 4, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \n  now() as 'time_sec',\n  COUNT(id) as 'value'\nFROM\n campaigns \n"
    }
   ]
  },
  {
   "title": "Voice Queues",
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 2, "w": 4, "x": 19, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \n  now() as 'time_sec',\n  COUNT(id) as 'value'\nFROM\n voice_queues \nWHERE \n  type='inbound'"
    }
   ]
  },
  {
   "title": "Dial State",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 3 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\r\n  now() as 'time_sec',\r\n\tCOUNT(dialActive) AS 'value',\r\n\tcase\r\n\t  when dialActive = '0' then 'Inactive'\r\n\t  else 'Active'\r\n\tend as 'metric'\r\nFROM \r\n\tvoice_queues\r\nwhere\r\n  type='outbound'\r\nGROUP BY\r\n\ttime_sec,metric\r\n"
    }
   ]
  },
  {
   "title": "Dial State",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 3 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\r\n  now() as 'time_sec',\r\n\tCOUNT(active) AS 'value',\r\n\tcase\r\n\t  when active = '0' then 'Inactive'\r\n\t  else 'Active'\r\n\tend as 'metric'\r\nFROM \r\n\tcampaigns\r\nGROUP BY\r\n\ttime_sec,metric\r\n"
    }
   ]
  },
  { "title": "Calls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Inbound Calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Call count" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  $__timeGroup(starttime,'1h') as time,\n  count(*) as value,\n  disposition as metric\nFROM motion2.report_call\nWHERE $__timeFilter(starttime) and type='inbound'\nGROUP BY disposition, $__timeGroup(starttime,'1h')\nORDER BY $__timeGroup(starttime,'1h') ASC"
    }
   ]
  },
  {
   "title": "Manual Outbound Calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Call count" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  $__timeGroup(starttime,'1h') as time,\n  count(*) as value,\n  disposition as metric\nFROM motion2.report_call\nWHERE $__timeFilter(starttime) and type='outbound'\nGROUP BY disposition, $__timeGroup(starttime,'1h')\nORDER BY $__timeGroup(starttime,'1h') ASC"
    }
   ]
  },
  {
   "title": "SLA Global",
   "type": "singlestat",
   "description": "% of answered calls",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 9 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \n  $__timeGroup(starttime,'1h') as time,\n  sum(if(disposition='ANSWERED', 1,0))/count(*)*100 as value\nFROM motion2.report_call\nWHERE $__timeFilter(starttime) and type in ('inbound','outbound','dialer')\nGROUP BY $__timeGroup(starttime,'1h')\nORDER BY $__timeGroup(starttime,'1h') ASC\n"
    }
   ]
  },
  {
   "title": "Last 10 calls",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT starttime as StartTime,\ntype as Type,\nCONCAT(SUBSTR(`source`,1, 6), '***') AS `From`,\n       CONCAT(SUBSTR(`destination`, 1, 6), '***') AS `To`,\n       duration as Duration,\n       disposition as Disposition\n  FROM motion2.report_call\n WHERE $__timeFilter(starttime)\n ORDER BY starttime desc\n LIMIT 10"
    }
   ]
  },
  {
   "title": "Queue Calls",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Call count" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  $__timeGroup(queuecallerjoinAt,'1h') as time,\n  SUM(CASE WHEN queuecallercomplete=1 THEN 1\n  WHEN queuecallerabandon=1 THEN 1\n  WHEN queuecallerexit=1 THEN 1 END) as value,\n  CASE WHEN queuecallercomplete=1 THEN \"Completed\"\n  WHEN queuecallerabandon=1 THEN \"Abandoned\"\n  WHEN queuecallerexit=1 THEN \"Unmanaged\" END as metric\nFROM motion2.report_queue\nWHERE $__timeFilter(queuecallerjoinAt)\nGROUP BY time,metric\nORDER BY $__timeGroup(queuecallerjoinAt,'1h') ASC\n"
    }
   ]
  },
  { "title": "Interactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Summary",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 28 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\nUNIX_TIMESTAMP() AS time_sec,\n  count(*) AS email\nFROM mail_interactions\nWHERE $__timeFilter(createdAt)\n\n"
    },
    {
     "rawSql": "SELECT\nUNIX_TIMESTAMP() AS time_sec,\n  count(*) AS chat\nFROM chat_interactions\nWHERE $__timeFilter(createdAt)\n"
    },
    {
     "rawSql": "SELECT\nUNIX_TIMESTAMP() AS time_sec,\n  count(*) AS sms\nFROM sms_interactions\nWHERE $__timeFilter(createdAt)"
    },
    {
     "rawSql": "SELECT\nUNIX_TIMESTAMP() AS time_sec,\n  count(*) AS social\nFROM openchannel_interactions\nWHERE $__timeFilter(createdAt)\n"
    },
    {
     "rawSql": "SELECT\nUNIX_TIMESTAMP() AS time_sec,\n  count(*) AS fax\nFROM fax_interactions\nWHERE $__timeFilter(createdAt)\n"
    }
   ]
  },
  {
   "title": "Mail Channel",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 6, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "Messages" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  $__timeGroup(createdAt,'1h') as time,\n  count(*) as value,\n  direction as metric\nFROM motion2.mail_messages\nWHERE $__timeFilter(createdAt)\nGROUP BY direction, $__timeGroup(createdAt,'1h')\nORDER BY $__timeGroup(createdAt,'1h') ASC,direction\n"
    }
   ]
  },
  {
   "title": "Chat Interactions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  $__timeGroup(createdAt,'1h') as time,\n  count(*) as value\nFROM motion2.chat_interactions\nWHERE $__timeFilter(createdAt)\nGROUP BY $__timeGroup(createdAt,'1h')\nORDER BY $__timeGroup(createdAt,'1h') ASC\n"
    }
   ]
  }
 ]
}