{
 "title": "Motion Bull IVR Campaigns",
 "time": { "from": "now/d", "to": "now/d" },
 "templating": {
  "list": [
   {
    "name": "campaign",
    "label": "Campaign",
    "query": "select id as __value, name as __text from campaigns"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Summary",
   "type": "table-old",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT \r\n\ta.name as 'Name',a.active,a.dialOriginateCallerIdNumber,a.dialGlobalInterval,b.name as 'Square Project',a.createdAt \r\nFROM \r\n  campaigns a,\r\n  square_projects b\r\nWHERE \r\n  a.id ='$campaign'\r\nAND a.SquareProjectId = b.id"
    }
   ]
  },
  { "title": "Hoppers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Total Hoppers",
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroup(scheduledAt,'1h') as time,\r\n  count(id)\r\nFROM cm_hopper\r\nWHERE\r\n campaignid ='$campaign'\r\nGROUP BY $__timeGroup(scheduledAt,'1h')"
    }
   ]
  },
  {
   "title": "Hoppers State",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 5 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\r\n  NOW() AS time_sec,\r\n  count(id) AS 'value',\r\n  CASE\r\n    WHEN active = 0 and countbusyretry = 0 and countcongestionretry = 0 and countnoanswerretry = 0 THEN \"Fresh\"\r\n    when active > 0 or countbusyretry > 0 or countcongestionretry > 0 or countnoanswerretry > 0 THEN \"Contacted\"\r\n  END AS metric\r\nFROM cm_hopper\r\nWHERE\r\n   campaignid = '$campaign'\r\nGROUP BY\r\n\tmetric"
    }
   ]
  },
  {
   "title": "Hoppers By List",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  COUNT(a.listid) AS 'value',\r\n  b.name AS metric\r\nFROM \r\n\tcm_hopper a,\r\n\tcm_lists b\r\nWHERE\r\n\ta.listid=b.id\r\n\tand campaignid='$campaign'\r\nGROUP BY metric"
    }
   ]
  },
  {
   "title": "Closed Selected Interval",
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time_sec,\n  COUNT(id) AS Closed \nFROM \n  cm_hopper_final \nWHERE \n  $__timeFilter(starttime)\n  AND campaignid='$campaign'\n"
    }
   ]
  },
  {
   "title": "Total Closed",
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time_sec,\n  COUNT(id) AS 'Closed' \nFROM \n  cm_hopper_final \nWHERE campaignid='$campaign'"
    }
   ]
  },
  {
   "title": "Fresh Hoppers",
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroup(scheduledAt,'1h') as time,\r\n  count(id)\r\nFROM cm_hopper\r\nWHERE\r\n   campaignid = '$campaign'\r\n  and\r\n    active = 0\r\n  and\r\n    countbusyretry = 0\r\n  and\r\n    countcongestionretry = 0\r\n  and\r\n    countnoanswerretry = 0\r\nGROUP BY $__timeGroup(scheduledAt,'1h')"
    }
   ]
  },
  {
   "title": "Calls Selected Interval",
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 9 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time_sec,\n  COUNT(id) AS Closed \nFROM \n  cm_hopper_history\nWHERE \n  $__timeFilter(starttime)\n  AND campaignid='$campaign'\n"
    }
   ]
  },
  {
   "title": "Total Called",
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 9 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time_sec,\n  COUNT(id) AS Closed \nFROM \n  cm_hopper_history\nWHERE \n  campaignid='$campaign'\n"
    }
   ]
  },
  { "title": "Hopper Final Call States", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Call States",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroup(starttime,'30m') as time,\r\n  count(statedesc) AS 'value',\r\n  case\r\n    when statedesc = 'Answer' then statedesc\r\n    else 'No Answer'\r\n  end AS 'metric'\r\nFROM \r\n\tcm_hopper_final\r\nWHERE\r\n   campaignid = '$campaign' AND starttime IS NOT null\r\nGROUP BY\r\n\ttime,metric\r\nORDER BY \r\n $__timeGroup(starttime,'30m')"
    }
   ]
  },
  {
   "title": "Selected Range Call States",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 14 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n\tNOW() AS 'time_sec',\n\tCOUNT(statedesc) AS 'value',\n\tstatedesc metric\nFROM \n\tcm_hopper_final\nWHERE\n\t$__timeFilter(starttime)\n\tAND campaignid='$campaign'\nGROUP BY\n\tmetric\n"
    }
   ]
  },
  {
   "title": "Total Call States",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 14 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n\tNOW() AS 'time_sec',\n\tCOUNT(statedesc) AS 'value',\n\tstatedesc metric\nFROM \n\tcm_hopper_final\nWHERE\n\tcampaignid='$campaign'\nGROUP BY\n\tmetric\n"
    }
   ]
  },
  { "title": "History Calls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Answer Calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroup(starttime,'1h') as time,\r\n  count(statedesc) AS 'value',\r\n  case\r\n    when statedesc = 'Answer' then statedesc\r\n    else 'No Answer'\r\n  end AS 'metric'\r\nFROM \r\n\tcm_hopper_history\r\nWHERE\r\n   campaignid = '$campaign' AND starttime IS NOT null\r\nGROUP BY\r\n\ttime,metric\r\nORDER BY \r\n $__timeGroup(starttime,'1h')"
    }
   ]
  },
  {
   "title": "Total Answer Calls",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 22 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroup(starttime,'1h') as time,\r\n  count(statedesc) AS 'value',\r\n\tcase\r\n     when statedesc = 'Answer' then statedesc\r\n     else 'No Answer'\r\n  end AS 'metric'\r\nFROM \r\n\tcm_hopper_history\r\nWHERE\r\n   campaignid = '$campaign' AND starttime IS NOT null\r\nGROUP BY\r\n\ttime,metric\r\nORDER BY \r\n $__timeGroup(starttime,'1h')"
    }
   ]
  },
  {
   "title": "Range Call States Detail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroup(starttime,'1h') as time,\r\n  count(statedesc) AS 'value',\r\n\tstatedesc AS 'metric'\r\nFROM \r\n\tcm_hopper_history\r\nWHERE\r\n   campaignid = '$campaign' AND starttime IS NOT null\r\nGROUP BY\r\n\ttime,metric\r\nORDER BY \r\n $__timeGroup(starttime,'1h')"
    }
   ]
  },
  {
   "title": "Total Range States",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 30 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroup(starttime,'1h') as time,\r\n  count(statedesc) AS 'value',\r\n\tstatedesc AS 'metric'\r\nFROM \r\n\tcm_hopper_history\r\nWHERE\r\n   campaignid = '$campaign' AND starttime IS NOT null\r\nGROUP BY\r\n\ttime,metric\r\nORDER BY \r\n $__timeGroup(starttime,'1h')"
    }
   ]
  }
 ]
}