{
 "title": "Motion Bull Campaign Details",
 "time": { "from": "now/d", "to": "now/d" },
 "templating": {
  "list": [
   {
    "name": "campaign",
    "label": "Campaign",
    "query": "select id as __value, name as __text from voice_queues where type='outbound'"
   }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Assigned",
     "type": "farski-blendstat-panel",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT \r\n  now() as 'time_sec',\r\n\tcount(a.name) as 'value'\r\nFROM \r\n\tusers a,\r\n\tuser_has_voice_queues b\r\nWHERE\r\n\tb.voicequeueid='$campaign'\r\n\tand\r\n\tb.userid=a.id"
      }
     ]
    },
    {
     "title": "Logged",
     "type": "farski-blendstat-panel",
     "gridPos": { "h": 2, "w": 7, "x": 4, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT \r\n  now() as 'time_sec',\r\n\tcount(a.name) AS 'value'\r\nFROM \r\n\tusers a,\r\n\tuser_has_voice_queues b\r\nWHERE\r\n\tb.voicequeueid='$campaign'\r\n\tAND (a.fullcontact IS NOT NULL AND a.fullcontact != '')\r\n\tAND b.userid=a.id\t"
      }
     ]
    },
    {
     "title": "Summary",
     "type": "table-old",
     "gridPos": { "h": 4, "w": 13, "x": 11, "y": 2 },
     "targets": [
      {
       "rawSql": "SELECT \n  dialActive,dialmethod,dialOriginateCallerIdNumber,\n  CASE \n    WHEN monitor_format = '' THEN 0\n    ELSE 1\n  END as record,\n  createdAt \nFROM \n  voice_queues \nWHERE \n  id='$campaign'"
      }
     ]
    },
    {
     "title": "Assigned",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 4 },
     "targets": [
      {
       "rawSql": "SELECT \r\n\ta.name AS Agent\r\nFROM \r\n\tusers a,\r\n\tuser_has_voice_queues b\r\nWHERE\r\n\tb.voicequeueid='$campaign'\r\n\tand\r\n\tb.userid=a.id"
      }
     ]
    },
    {
     "title": "Logged In",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 7, "x": 4, "y": 4 },
     "targets": [
      {
       "rawSql": "SELECT \r\n\ta.name AS Agent,\r\n\ta.ipaddr AS 'Ip Address',\r\n\ta.useragent as 'User Agent'\r\nFROM \r\n\tusers a,\r\n\tuser_has_voice_queues b\r\nWHERE\r\n\tb.voicequeueid='$campaign'\r\n\tAND (a.fullcontact IS NOT NULL AND a.fullcontact != '')\r\n\tAND b.userid=a.id\t"
      }
     ]
    },
    {
     "title": "Total Calls",
     "type": "farski-blendstat-panel",
     "gridPos": { "h": 6, "w": 3, "x": 11, "y": 6 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  now() as 'time_sec',\n  count(id) as 'value'\nFROM \n  cm_hopper_history\nWHERE\n  $__timeFilter(starttime) and voicequeueid='$campaign'\n"
      }
     ]
    },
    {
     "title": "Answered",
     "type": "farski-blendstat-panel",
     "gridPos": { "h": 3, "w": 4, "x": 14, "y": 6 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  now() as 'time_sec',\n  count(id) as 'value'\nFROM \n  cm_hopper_history\nWHERE\n  $__timeFilter(starttime) and state = 4 and voicequeueid='$campaign'\n"
      }
     ]
    },
    {
     "title": "Dropped ",
     "type": "farski-blendstat-panel",
     "gridPos": { "h": 6, "w": 2, "x": 18, "y": 6 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  now() as 'time_sec',\n  count(id) as 'value'\nFROM \n  cm_hopper_history\nWHERE\n  $__timeFilter(starttime) and state=10 and voicequeueid='$campaign'\n"
      }
     ]
    },
    {
     "title": "Abandoned ",
     "type": "farski-blendstat-panel",
     "gridPos": { "h": 6, "w": 2, "x": 20, "y": 6 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  now() as 'time_sec',\n  count(id) as 'value'\nFROM \n  cm_hopper_history\nWHERE\n  $__timeFilter(starttime) and state=11 and voicequeueid='$campaign'\n"
      }
     ]
    },
    {
     "title": "BlackList",
     "type": "farski-blendstat-panel",
     "gridPos": { "h": 6, "w": 2, "x": 22, "y": 6 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  now() as 'time_sec',\n  count(id) as 'value'\nFROM \n  cm_hopper_history\nWHERE\n  $__timeFilter(starttime) and state=13 and voicequeueid='$campaign'\n"
      }
     ]
    },
    {
     "title": "Unmanaged",
     "type": "farski-blendstat-panel",
     "gridPos": { "h": 3, "w": 4, "x": 14, "y": 9 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  now() as 'time_sec',\n  count(id) as 'value'\nFROM \n  cm_hopper_history\nWHERE\n  $__timeFilter(starttime) and state !=4 and voicequeueid='$campaign'\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Hoppers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Hoppers",
     "type": "farski-blendstat-panel",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "rawSql": "SELECT\r\n  $__timeGroup(scheduledAt,'1h') as time,\r\n  count(id)\r\nFROM cm_hopper\r\nWHERE\r\n   voiceQueueId ='$campaign'\r\nGROUP BY $__timeGroup(scheduledAt,'1h')"
      }
     ]
    },
    {
     "title": "Hoppers State",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 11, "w": 5, "x": 5, "y": 2 },
     "format": "short",
     "valueName": "total",
     "targets": [
      {
       "rawSql": "SELECT\r\n  NOW() AS time_sec,\r\n  count(id) AS 'value',\r\n  CASE\r\n    WHEN active = 0 and countbusyretry = 0 and countcongestionretry = 0 and countnoanswerretry = 0 THEN \"Fresh\"\r\n    when active > 0 or countbusyretry > 0 or countcongestionretry > 0 or countnoanswerretry > 0 THEN \"Contacted\"\r\n  END AS metric\r\nFROM cm_hopper\r\nWHERE\r\n   voiceQueueId = '$campaign'\r\nGROUP BY\r\n\tmetric"
      }
     ]
    },
    {
     "title": "Hoppers By List",
     "type": "table-old",
     "gridPos": { "h": 11, "w": 4, "x": 10, "y": 2 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  COUNT(a.listid) AS 'value',\r\n  b.name AS metric\r\nFROM \r\n\tcm_hopper a,\r\n\tcm_lists b\r\nWHERE\r\n\ta.listid=b.id\r\n\tand voicequeueid='$campaign'\r\nGROUP BY metric"
      }
     ]
    },
    {
     "title": "New Hoppers by List",
     "type": "table",
     "gridPos": { "h": 11, "w": 5, "x": 14, "y": 2 },
     "targets": [
      {
       "rawSql": "SELECT \r\n\ta.name,\r\n\tCOUNT(b.listid) AS total\r\nFROM \r\n\tcm_lists a,\r\n\tcm_hopper b\r\nWHERE\r\n  b.ListId=a.id\r\n  and b.countbusyretry = 0 and b.countcongestionretry = 0 and b.countnoanswerretry = 0\r\n  and b.countnosuchnumberretry = 0 and b.countdropretry = 0 and b.countabandonedretry = 0 and b.countmachineretry = 0\r\n  and b.countagentrejectretry = 0\r\n  AND b.priority > 1\r\n  AND b.voicequeueid='$campaign'\r\nGROUP BY\r\n\ta.name,b.listid;"
      }
     ]
    },
    {
     "title": "Closed Selected Interval",
     "type": "farski-blendstat-panel",
     "gridPos": { "h": 4, "w": 3, "x": 19, "y": 2 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "rawSql": "SELECT\n  now() as time_sec,\n  COUNT(id) AS Closed \nFROM \n  cm_hopper_final \nWHERE \n  $__timeFilter(starttime)\n  AND voicequeueid='$campaign'\n"
      }
     ]
    },
    {
     "title": "Total Closed",
     "type": "farski-blendstat-panel",
     "gridPos": { "h": 4, "w": 2, "x": 22, "y": 2 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "rawSql": "SELECT\n  now() as time_sec,\n  COUNT(id) AS 'Closed' \nFROM \n  cm_hopper_final \nWHERE voicequeueid='$campaign'"
      }
     ]
    },
    {
     "title": "Fresh Hoppers",
     "type": "farski-blendstat-panel",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "rawSql": "SELECT\r\n  now() as time_sec,\r\n  count(id)\r\nFROM cm_hopper\r\nWHERE\r\n   voiceQueueId = '$campaign'\r\n  and active = 0 and countbusyretry = 0 and countcongestionretry = 0 and countnoanswerretry = 0\r\n  and countnosuchnumberretry = 0 and countdropretry = 0 and countabandonedretry = 0 and countmachineretry = 0\r\n  and countagentrejectretry = 0"
      }
     ]
    },
    {
     "title": "Calls Selected Interval",
     "type": "farski-blendstat-panel",
     "gridPos": { "h": 4, "w": 3, "x": 19, "y": 6 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "rawSql": "SELECT\n  now() as time_sec,\n  COUNT(id) AS Closed \nFROM \n  cm_hopper_history\nWHERE \n  $__timeFilter(starttime)\n  AND voicequeueid='$campaign'\n"
      }
     ]
    },
    {
     "title": "Total Called",
     "type": "farski-blendstat-panel",
     "gridPos": { "h": 4, "w": 2, "x": 22, "y": 6 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "rawSql": "SELECT\n  now() as time_sec,\n  COUNT(id) AS Closed \nFROM \n  cm_hopper_history\nWHERE \n  voicequeueid='$campaign'\n"
      }
     ]
    },
    {
     "title": "Unmanaged Recall Me",
     "type": "farski-blendstat-panel",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 9 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "rawSql": "SELECT\r\n  now() as time_sec,\r\n  count(voiceQueueId)\r\nFROM cm_hopper\r\nWHERE\r\n   voiceQueueId = '$campaign'\r\n  and Userid is null and recallme =1"
      }
     ]
    }
   ]
  },
  {
   "title": "Hopper Final Call States & Dispositions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Range Sales",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 3 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "rawSql": "SELECT\n  now() as 'time_sec',\n  COUNT(disposition) as 'value'\nFROM cm_hopper_final\nWHERE\n  $__timeFilter(starttime) and lcase(disposition) like '%venta' and voicequeueid='$campaign'\n"
      }
     ]
    },
    {
     "title": "Total Sales",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 3 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "rawSql": "SELECT\n  now() as 'time_sec',\n  COUNT(disposition) as 'value'\nFROM cm_hopper_final\nWHERE\n  lcase(disposition) = 'acepta contrato' and voicequeueid='$campaign'\n"
      }
     ]
    },
    {
     "title": "Selected Range Dispositions",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
     "format": "short",
     "valueName": "total",
     "targets": [
      {
       "rawSql": "SELECT\n\tNOW() AS 'time_sec',\n\tCOUNT(disposition) AS 'value',\n\tCASE\n\t\tWHEN disposition IS NULL THEN 'Not Disposed'\n\t\tELSE disposition\n\tEND AS metric\nFROM \n\tcm_hopper_final\nWHERE\n\t$__timeFilter(starttime)\n\tAND voicequeueid='$campaign'\nGROUP BY\n\tmetric\n\t"
      }
     ]
    },
    {
     "title": "Selected Range Call States",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 6 },
     "format": "short",
     "valueName": "total",
     "targets": [
      {
       "rawSql": "SELECT\n\tNOW() AS 'time_sec',\n\tCOUNT(statedesc) AS 'value',\n\tstatedesc as 'metric'\nFROM \n\tcm_hopper_final\nWHERE\n\t$__timeFilter(starttime)\n\tAND voicequeueid='$campaign'\nGROUP BY\n\tmetric\n"
      }
     ]
    },
    {
     "title": "Total Closed Dispositions",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 6 },
     "format": "short",
     "valueName": "total",
     "targets": [
      {
       "rawSql": "SELECT\n\tNOW() AS 'time_sec',\n\tCOUNT(disposition) AS 'value',\n\tCASE\n\t\tWHEN disposition IS NULL THEN 'Not Disposed'\n\t\tELSE disposition\n\tEND AS metric\nFROM \n\tcm_hopper_final\nWHERE\n\tvoicequeueid='$campaign'\n\tAND disposition NOT IN ('recallme','reschedule')\nGROUP BY\n\tmetric\n\t"
      }
     ]
    },
    {
     "title": "Total Call States",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 6 },
     "format": "short",
     "valueName": "total",
     "targets": [
      {
       "rawSql": "SELECT\n\tNOW() AS 'time_sec',\n\tCOUNT(statedesc) AS 'value',\n\tstatedesc metric\nFROM \n\tcm_hopper_final\nWHERE\n\tvoicequeueid='$campaign'\nGROUP BY\n\tmetric\n"
      }
     ]
    },
    {
     "title": "Dispositions By Hour",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT \n  $__timeGroup(starttime,'1h') as time,\n  count(disposition) as value,\n  disposition as metric\nFROM \n  cm_hopper_final\nWHERE \n    $__timeFilter(starttime) \n  and \n    voicequeueid = '$campaign'\nGROUP BY \n  metric, $__timeGroup(starttime,'1h')\nORDER BY \n$__timeGroup(starttime,'1h') ASC"
      }
     ]
    },
    {
     "title": "Dispositions By Agent",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT \n  $__timeGroup(starttime,'1h') as time,\n  count(membername) as value,\n  membername as metric\nFROM \n  cm_hopper_final\nWHERE \n    $__timeFilter(starttime) \n  and \n    voicequeueid = '$campaign'\nGROUP BY \n  metric, $__timeGroup(starttime,'1h')\nORDER BY \n$__timeGroup(starttime,'1h') ASC"
      }
     ]
    },
    {
     "title": "Agent Sales",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT \r\n  $__timeGroup(starttime,'1h') as time,\r\n  count(membername) as value,\r\n  membername as metric\r\nFROM \r\n  cm_hopper_final\r\nWHERE \r\n    $__timeFilter(starttime) \r\n\tand \r\n    voicequeueid = '$campaign'\r\n\tand\r\n\t LCASE(disposition) = 'acepta contrato'\r\nGROUP BY \r\n  metric, $__timeGroup(starttime,'1h')\r\nORDER BY \r\n$__timeGroup(starttime,'1h') ASC"
      }
     ]
    }
   ]
  },
  {
   "title": "History Calls",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Answer Calls",
     "type": "graph",
     "gridPos": { "h": 8, "w": 19, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\r\n  $__timeGroup(starttime,'1h') as time,\r\n  count(statedesc) AS 'value',\r\n  case\r\n    when statedesc = 'Answer' then statedesc\r\n    else 'No Answer'\r\n  end AS 'metric'\r\nFROM \r\n\tcm_hopper_history\r\nWHERE\r\n   voiceQueueId = '$campaign' AND starttime IS NOT null\r\nGROUP BY\r\n\ttime,metric\r\nORDER BY \r\n $__timeGroup(starttime,'1h')"
      }
     ]
    },
    {
     "title": "Total Range States",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 4 },
     "format": "short",
     "valueName": "total",
     "targets": [
      {
       "rawSql": "SELECT\r\n  $__timeGroup(starttime,'1h') as time,\r\n  count(statedesc) AS 'value',\r\n\tcase\r\n     when statedesc = 'Answer' then statedesc\r\n     else 'No Answer'\r\n  end AS 'metric'\r\nFROM \r\n\tcm_hopper_history\r\nWHERE\r\n   voiceQueueId = '$campaign' \r\n   AND $__timeFilter(starttime)\r\nGROUP BY\r\n\ttime,metric\r\nORDER BY \r\n $__timeGroup(starttime,'1h')"
      }
     ]
    },
    {
     "title": "Range Call States Detail",
     "type": "graph",
     "gridPos": { "h": 9, "w": 14, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\r\n  $__timeGroup(starttime,'1h') as time,\r\n  count(statedesc) AS 'value',\r\n\tstatedesc AS 'metric'\r\nFROM \r\n\tcm_hopper_history\r\nWHERE\r\n   voiceQueueId = '$campaign' AND starttime IS NOT null\r\nGROUP BY\r\n\ttime,metric\r\nORDER BY \r\n $__timeGroup(starttime,'1h')"
      }
     ]
    },
    {
     "title": "Total Range States Detail",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 9, "w": 5, "x": 14, "y": 12 },
     "format": "short",
     "valueName": "total",
     "targets": [
      {
       "rawSql": "SELECT\r\n  $__timeGroup(starttime,'1h') as time,\r\n  count(statedesc) AS 'value',\r\n\tstatedesc AS 'metric'\r\nFROM \r\n\tcm_hopper_history\r\nWHERE\r\n   voiceQueueId = '$campaign' AND $__timeFilter(starttime)\r\nGROUP BY\r\n\ttime,metric\r\nORDER BY \r\n $__timeGroup(starttime,'1h')"
      }
     ]
    },
    {
     "title": "Total States",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 9, "w": 5, "x": 19, "y": 12 },
     "format": "short",
     "valueName": "total",
     "targets": [
      {
       "rawSql": "SELECT\r\n  $__timeGroup(starttime,'1h') as time,\r\n  count(statedesc) AS 'value',\r\n\tstatedesc AS 'metric'\r\nFROM \r\n\tcm_hopper_history\r\nWHERE\r\n   voiceQueueId = '$campaign' AND starttime IS NOT null\r\nGROUP BY\r\n\ttime,metric\r\nORDER BY \r\n $__timeGroup(starttime,'1h')"
      }
     ]
    }
   ]
  },
  {
   "title": "Lists",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Loaded Lists",
     "type": "table",
     "gridPos": { "h": 17, "w": 8, "x": 0, "y": 5 },
     "targets": [
      {
       "rawSql": "SELECT DISTINCT(a.listid),b.name FROM cm_hopper a, cm_lists b WHERE a.listid=b.id AND a.voicequeueid='$campaign'"
      }
     ]
    }
   ]
  }
 ]
}