{
 "title": "Motion Bull Global",
 "time": { "from": "now/d", "to": "now/d" },
 "panels": [
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Campaigns",
     "type": "table-old",
     "gridPos": { "h": 14, "w": 9, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT NAME,dialActive,dialMethod,dialOriginateCallerIdNumber,id FROM voice_queues WHERE TYPE='outbound' order by NAME ASC"
      }
     ]
    },
    {
     "title": "Agents per Campaign",
     "type": "table-old",
     "gridPos": { "h": 14, "w": 6, "x": 9, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT \r\n\tCOUNT(a.userId) AS 'value',\r\n\tb.name AS 'metric'\r\nFROM \r\n\tuser_has_voice_queues a,\r\n\tvoice_queues b\r\nWHERE \r\n\ta.VoiceQueueId = b.id\r\n\tand b.type='outbound'\r\nGROUP BY \r\n\tmetric\r\nORDER BY metric ASC"
      }
     ]
    },
    {
     "title": "Campaign Dial Method",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 6, "w": 4, "x": 15, "y": 1 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "SELECT \r\n  now() as 'time_sec',\r\n\tCount(dialMethod) AS 'value',\r\n\tdialMethod AS 'metric'\r\nFROM \r\n\tvoice_queues \r\nWHERE \r\n\ttype='outbound'\r\nGROUP BY \r\n\tmetric"
      }
     ]
    },
    {
     "title": "Agents Available",
     "type": "farski-blendstat-panel",
     "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  now() as 'time_sec',\n  count(online) as 'value'\nFROM \n  users\nWHERE\n  online=1"
      }
     ]
    },
    {
     "title": "Available agents",
     "type": "table-old",
     "gridPos": { "h": 11, "w": 5, "x": 19, "y": 4 },
     "targets": [
      {
       "rawSql": "SELECT\n  name AS \"login\",\n  fullname as \"user\"\nFROM \n  users\nWHERE\n  online='1'\n  and role='agent'"
      }
     ]
    },
    {
     "title": "Campaigs Status",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 5, "w": 4, "x": 15, "y": 7 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "SELECT \r\n  now() as 'time_sec',\r\n\tCount(dialActive) AS 'value',\r\n\tCASE\r\n\t WHEN dialActive='1' THEN 'Active'\r\n\t ELSE 'Inactive'\r\n\tEND AS 'metric'\r\nFROM \r\n\tvoice_queues \r\nWHERE \r\n\ttype='outbound'\r\nGROUP BY \r\n\tmetric"
      }
     ]
    },
    {
     "title": "Campaigs Status",
     "type": "bargauge",
     "gridPos": { "h": 3, "w": 4, "x": 15, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "SELECT \r\n  now() as 'time_sec',\r\n\tCount(dialActive) AS 'value',\r\n\tCASE\r\n\t WHEN dialActive='1' THEN 'Active'\r\n\t ELSE 'Inactive'\r\n\tEND AS 'metric'\r\nFROM \r\n\tvoice_queues \r\nWHERE \r\n\ttype='outbound'\r\nGROUP BY \r\n\tmetric"
      }
     ]
    }
   ]
  },
  {
   "title": "Dispositions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Campaign Sales",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 2 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "SELECT \n\tNOW() AS 'time_sec',\n\tCOUNT(a.voicequeueid) AS 'value',\n\tb.name AS 'metric'\nFROM\n\tcm_hopper_final a,\n\tvoice_queues b\nWHERE\n\t$__timeFilter(a.starttime)\n\tAND LCASE(a.disposition) = 'acepta contrato'\n\tAND a.VoiceQueueId = b.id\nGROUP BY\n\tmetric;\n"
      }
     ]
    },
    {
     "title": "Total Sales",
     "type": "farski-blendstat-panel",
     "gridPos": { "h": 4, "w": 4, "x": 10, "y": 2 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "rawSql": "SELECT\n  now() as 'time_sec',\n  count(id) as 'value'\nFROM \n  cm_hopper_final\nWHERE\n  $__timeFilter(starttime)\n  AND lcase(disposition)='acepta contrato'\n"
      }
     ]
    },
    {
     "title": "Total Dispositions",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 2 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "SELECT \n\tNOW() AS 'time_sec',\n\tCOUNT(disposition) AS 'value',\n\tdisposition AS 'metric'\nFROM\n\tcm_hopper_final\nWHERE\n\t$__timeFilter(starttime)\n\tAND disposition IS NOT null\nGROUP BY\n\tmetric;\n"
      }
     ]
    },
    {
     "title": "Total Dispositions",
     "type": "farski-blendstat-panel",
     "gridPos": { "h": 4, "w": 4, "x": 10, "y": 6 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "rawSql": "SELECT\n  now() as 'time_sec',\n  count(id) as 'value'\nFROM \n  cm_hopper_final\nWHERE\n  $__timeFilter(starttime)\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Calls",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Calls per Campaign",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 3 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "SELECT \n\tnow() as 'time_sec',\n\tCount(VoiceQueueId) AS 'value',\n\tb.name AS 'metric'\nFROM \n\tcm_hopper_history a,\n\tvoice_queues b\nWHERE \n\t$__timeFilter(starttime)\n\tAND a.voiceQueueId = b.id\nGROUP BY metric\n"
      }
     ]
    },
    {
     "title": "Total Calls",
     "type": "farski-blendstat-panel",
     "gridPos": { "h": 2, "w": 4, "x": 10, "y": 3 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "rawSql": "SELECT\n  now() as 'time_sec',\n  count(id) as 'value'\nFROM \n  cm_hopper_history\nWHERE\n  $__timeFilter(starttime)\n"
      }
     ]
    },
    {
     "title": "Call Results",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 3 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "SELECT \n\tNOW() AS 'time_sec',\n\tCOUNT(statedesc) AS 'value',\n\tstatedesc AS 'metric'\nFROM \n\tcm_hopper_history\nWHERE \n\t$__timeFilter(starttime)\nGROUP BY time_sec, metric\n"
      }
     ]
    },
    {
     "title": "Answered Calls",
     "type": "farski-blendstat-panel",
     "gridPos": { "h": 3, "w": 4, "x": 10, "y": 5 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "rawSql": "SELECT\n  now() as 'time_sec',\n  count(id) as 'value'\nFROM \n  cm_hopper_history\nWHERE\n  $__timeFilter(starttime) and state = 4\n"
      }
     ]
    },
    {
     "title": "Unswered Calls",
     "type": "farski-blendstat-panel",
     "gridPos": { "h": 3, "w": 4, "x": 10, "y": 8 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "rawSql": "SELECT\n  now() as 'time_sec',\n  count(id) as 'value'\nFROM \n  cm_hopper_history\nWHERE\n  $__timeFilter(starttime) and state != 4\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Hoppers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Hoppers",
     "type": "farski-blendstat-panel",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "SELECT\r\n  now() as 'time_sec',\r\n  count(id)\r\nFROM cm_hopper"
      }
     ]
    },
    {
     "title": "Hoppers By Campaign",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 10, "w": 10, "x": 4, "y": 4 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "SELECT\r\n  NOW() as time,\r\n  COUNT(a.voicequeueid) AS 'value',\r\n  b.name AS metric\r\nFROM \r\n\tcm_hopper a,\r\n\tvoice_queues b\r\nWHERE\r\n\ta.voicequeueid=b.id\r\nGROUP BY metric\r\nORDER BY metric ASC"
      }
     ]
    },
    {
     "title": "New  Hoppers By Campaign",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 10, "w": 10, "x": 14, "y": 4 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "SELECT\r\n  NOW() as time,\r\n  COUNT(a.voicequeueid) AS 'value',\r\n  b.name AS metric\r\nFROM \r\n\tcm_hopper a,\r\n\tvoice_queues b\r\nWHERE\r\n\ta.voicequeueid=b.id\r\n\tand a.active = 0\r\n  and a.countbusyretry = 0\r\n  and a.countcongestionretry = 0\r\n  and a.countnoanswerretry = 0\r\nGROUP BY metric\r\nORDER BY metric ASC"
      }
     ]
    },
    {
     "title": "New Hoppers",
     "type": "farski-blendstat-panel",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 9 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\r\n  now() as time,\r\n  count(id)\r\nFROM cm_hopper\r\nWHERE\r\n    active = 0\r\n  and\r\n    countbusyretry = 0\r\n  and\r\n    countcongestionretry = 0\r\n  and\r\n    countnoanswerretry = 0"
      }
     ]
    },
    {
     "title": "Hoppers By List",
     "type": "table-old",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  COUNT(a.listid) AS 'value',\r\n  b.name AS metric\r\nFROM \r\n\tcm_hopper a,\r\n\tcm_lists b\r\nWHERE\r\n\ta.listid=b.id\r\nGROUP BY metric"
      }
     ]
    },
    {
     "title": "Hoppers By List",
     "type": "table-old",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  COUNT(a.listid) AS 'value',\r\n  b.name AS metric\r\nFROM \r\n\tcm_hopper a,\r\n\tcm_lists b\r\nWHERE\r\n\ta.listid=b.id\r\n\tand a.active = 0\r\n  and a.countbusyretry = 0\r\n  and a.countcongestionretry = 0\r\n  and a.countnoanswerretry = 0\r\nGROUP BY metric"
      }
     ]
    }
   ]
  }
 ]
}