{
 "title": "xCally Calls Details",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "LLamadas por tipo",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  now() AS \"time\",\n  `type` as name,\n  COUNT(`type`) as value\nFROM report_call\nWHERE\n  $__timeFilter(starttime)\n  AND `type` IS NOT NULL\t\ngroup BY `type`\n"
    }
   ]
  },
  {
   "title": "Total emitidas",
   "type": "singlestat",
   "description": "Este panel muestra todas las llamadas emitidas, tanto de marcador como manuales",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(starttime,'1h') as time,\n  count(type) as value\nFROM report_call\nWHERE\n  $__timeFilter(starttime)\n  AND TYPE IN('outbound','dialer')\nGROUP BY $__timeGroup(starttime,'1h')\nORDER BY $__timeGroup(starttime,'1h') ASC  \n"
    }
   ]
  },
  {
   "title": "Total llamadas emitidas",
   "type": "table-old",
   "description": "Panel que muestra el total de las llamadas emitidas manuales y de marcador, indicando cuantas son facturables para cada tipo",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n\tTYPE,\n\tCOUNT(TYPE) AS total,\n\t(\n\t\tCASE\n\t\t\tWHEN billableseconds > 0 THEN \"billed\"\n\t\t\tELSE \"Not billed\" \n\t\tEND\n\t) AS billable\nFROM \n\treport_call \nWHERE \n\t$__timeFilter(starttime)\n\tAND TYPE IN('dialer','outbound')\nGROUP BY TYPE,billable"
    }
   ]
  },
  {
   "title": "Total Recibidas",
   "type": "singlestat",
   "description": "Este panel muestra todas las llamadas emitidas, tanto de marcador como manuales",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 3 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(starttime,'1h') as time,\n  count(type) as value\nFROM report_call\nWHERE\n  $__timeFilter(starttime)\n  AND TYPE IN('inbound')\nGROUP BY $__timeGroup(starttime,'1h')\nORDER BY $__timeGroup(starttime,'1h') ASC  \n"
    }
   ]
  },
  {
   "title": "Coste APROXIMADO de llamadas",
   "type": "table-old",
   "description": "Cuadro que muestra un coste \"aproximado\" de las llamadas emitidas en el tramo seleccionado",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT \n\tt2.*,\n\tSEC_TO_TIME(t2.seconds) AS total,\n\t(\n\t\tcase\n\t\t when t2.phone = 'mobile' then (t2.seconds/60) * 0.03\n\t\t else (t2.seconds/60) * 0.01\n\t\tend\n\t) AS cost\nFROM \n(\nSELECT\n\tsum(billableseconds) AS seconds,\n\t(\n\t\tCASE\n\t\t\tWHEN destination LIKE '9%' THEN \"phone\"\n\t\t\tWHEN destination LIKE '6%' THEN \"mobile\"\n\t\t\tELSE \"others\" \n\t\tEND\n\t) AS phone\nFROM \n\treport_call \nWHERE \n\t$__timeFilter(starttime)\n\tAND TYPE IN('dialer','outbound')\n\tAND billableseconds > 0\nGROUP BY phone\n) AS t2"
    }
   ]
  }
 ]
}