{
 "title": "xCally Lists",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "list",
    "label": "List",
    "query": "select id as __value, name as __text from cm_lists"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Contacts",
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select \n  now() as 'time_sec',\n  count(1)as 'value'\n  from cm_contacts where listid='$list'"
    }
   ]
  },
  {
   "title": "NoSuchNumber",
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \r\n  now() as 'time_sec',\r\n  COUNT(1) as 'value'\r\n  FROM \r\n(\r\n\tSELECT DISTINCT(calleridnum)  AS total\r\n\tFROM \tcm_hopper_final \r\n\tWHERE \r\n\t\tListid='$list'\r\n\t\tAND `state`=0\r\n) t"
    }
   ]
  },
  {
   "title": "Range Dispositions",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 5, "x": 7, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT \r\n  now() as 'time_sec',\r\n\tCOUNT(disposition) AS 'value', \r\n\tdisposition AS 'metric'\r\nFROM\r\n\tcm_hopper_final\r\nWHERE \r\n  listid='$list' AND disposition IS NOT null and $__timeFilter(createdAt)\r\nGROUP BY disposition"
    }
   ]
  },
  {
   "title": "Total Dispositions",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 7, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT \r\n  now() as 'time_sec',\r\n\tCOUNT(disposition) AS 'value', \r\n\tdisposition AS 'metric'\r\nFROM\r\n\tcm_hopper_final\r\nWHERE listid='$list' AND disposition IS NOT null\r\nGROUP BY disposition"
    }
   ]
  },
  {
   "title": "Call State Range",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 5, "x": 19, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\r\n  now() as time_sec,\r\n  count(statedesc) AS 'value',\r\n\tcase\r\n     when statedesc = 'Answer' then statedesc\r\n     else 'No Answer'\r\n  end AS 'metric'\r\nFROM \r\n\tcm_hopper_history\r\nWHERE\r\n   listid = '$list' \r\n   AND $__timeFilter(starttime)\r\nGROUP BY\r\n\ttime_sec,metric"
    }
   ]
  },
  {
   "title": "Disposed Contacts",
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \r\n  now() as 'time_sec',\r\n  COUNT(1) AS 'value' \r\nFROM\r\n\t(\r\n\t\tSELECT \r\n\t\t\tdistinct(calleridnum)\r\n\t\tFROM \r\n\t\t\tcm_hopper_final \r\n\t\tWHERE \r\n\t\t\tlistid='$list'\r\n\t) t"
    }
   ]
  },
  {
   "title": "Contacts called",
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \r\n\tNOW() AS 'time_sec',\r\n\tCOUNT(1) \r\nFROM cm_hopper_history WHERE listid='$list'"
    }
   ]
  },
  {
   "title": "Available Contacts",
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \r\n  now() as 'time_sec',\r\n  COUNT(1) AS 'total' \r\n  FROM cm_contacts WHERE id NOT IN\r\n(\r\n\tSELECT \r\n\t\tdistinct(contactid)\r\n\tFROM \r\n\t\tcm_hopper_final \r\n\tWHERE \r\n\t\tlistid='$list'\r\n)\r\nAND listid='$list'"
    }
   ]
  },
  {
   "title": "Contacts called ?????",
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \r\n\tNOW() AS 'time_sec',\r\n\tCOUNT(1) \r\nFROM \r\n(\r\n  select distinct(calleridnum) from cm_hopper_history WHERE listid='$list'\r\n) t"
    }
   ]
  },
  {
   "title": "Fresh Contacts",
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\r\n  now() as time_sec,\r\n  count(id)\r\nFROM cm_hopper\r\nWHERE\r\n\tcountbusyretry = 0 and countcongestionretry = 0 and countnoanswerretry = 0\r\n  and countnosuchnumberretry = 0 and countdropretry = 0 and countabandonedretry = 0 and countmachineretry = 0\r\n  and countagentrejectretry = 0\r\n  AND listid='$list'"
    }
   ]
  },
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Range Dispositions",
     "type": "table",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 11 },
     "targets": [
      {
       "rawSql": "SELECT \r\n\tCOUNT(disposition) AS 'value', \r\n\tdisposition AS 'metric'\r\nFROM\r\n\tcm_hopper_final\r\nWHERE \r\n  listid='$list' AND disposition IS NOT null and $__timeFilter(createdAt)\r\nGROUP BY disposition"
      }
     ]
    },
    {
     "title": "Total Dispositions",
     "type": "table",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 11 },
     "targets": [
      {
       "rawSql": "SELECT \r\n\tCOUNT(disposition) AS 'value', \r\n\tdisposition AS 'metric'\r\nFROM\r\n\tcm_hopper_final\r\nWHERE \r\n  listid='$list' AND disposition IS NOT null \r\nGROUP BY disposition"
      }
     ]
    },
    {
     "title": "Menor de edad  - Persona muy mayor - Ilocalizable - No existe",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "rawSql": "SELECT \r\n\ta.firstName,a.lastName,a.phone,a.cf_1 AS provider,a.cf_4 AS provider_base,\r\n\tb.disposition\r\nFROM \r\n\tcm_contacts a,\r\n\tcm_hopper_final b\r\nWHERE\r\n\ta.id=b.contactid\r\n\tAND b.listid='$list' AND b.disposition IN ('Menor de edad','Persona muy mayor','Ilocalizable','No existe');"
      }
     ]
    }
   ]
  },
  {
   "title": "Dispositions and NoSuchNumber",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dispositions per list with custom fields",
     "type": "table",
     "gridPos": { "h": 11, "w": 11, "x": 0, "y": 7 },
     "targets": [
      {
       "rawSql": "SELECT \r\n\ta.disposition,\r\n\tcount(a.disposition) AS total,\r\n\tc.name,\r\n\tb.cf_1 AS proveedor,\r\n\tb.cf_4 AS provider_base\r\nFROM\r\n\tcm_hopper_final a,\r\n\tcm_contacts b,\r\n\tcm_lists c\r\nWHERE \r\n\tb.id=a.contactid\r\n\tAND a.listid = c.id\r\n\tAND $__timeFilter(starttime)\r\nGROUP BY\r\n\ta.listid,\r\n\ta.disposition,\r\n\tb.cf_1,\r\n\tb.cf_4\r\nHAVING \r\n\ttotal > 0\r\nORDER BY\r\n\ta.disposition ASC"
      }
     ]
    },
    {
     "title": "No Such Number",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 11, "y": 7 },
     "targets": [
      {
       "rawSql": "SELECT \r\n\tCOUNT(a.id) AS 'total calls',\r\n\ta.calleridnum,\r\n\ta.listid,\r\n\tc.name,\r\n\ta.contactid,\r\n\tb.cf_1 AS 'provider',\r\n\tb.cf_4 AS 'provider_base'\r\nFROM \r\n\tcm_hopper_history a,\r\n\tcm_contacts b,\r\n\tcm_lists c\r\nWHERE \r\n\ta.contactid=b.id\r\n\tAND a.listid=c.id\r\n\tAND a.state=0\r\n\tAND $__timeFilter(starttime)\r\nGROUP BY\r\n\ta.calleridnum,\r\n\ta.listid,\r\n\ta.contactid,\r\n\tb.cf_1,\r\n\tb.cf_4\r\nHAVING COUNT(a.id) >= 1"
      }
     ]
    }
   ]
  }
 ]
}