{
 "title": "xCally Voice Queues",
 "time": { "from": "now/d", "to": "now/d" },
 "templating": {
  "list": [
   {
    "name": "queue",
    "label": "Queue",
    "query": "select name from voice_queues where type='inbound';"
   }
  ]
 },
 "panels": [
  {
   "title": "Voice Queue Calls",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Incoming Queue Calls",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT \n  $__timeGroup(queuecallerjoinAt,'15m') as time,\n  SUM(CASE WHEN queuecallerabandon=1 THEN 1\n  WHEN queuecallerexit=1 THEN 1\n  WHEN queuecallercomplete=1 THEN 1\n   END) as value,\n  CASE WHEN queuecallercomplete=1 THEN \"Completed\"\n  WHEN queuecallerabandon=1 THEN \"Abandoned\"\n  WHEN queuecallerexit=1 THEN \"Unmanaged\" END as metric\nFROM motion2.report_queue\nWHERE $__timeFilter(queuecallerjoinAt)\nGROUP BY time,metric\nORDER BY $__timeGroup(queuecallerjoinAt,'15m') ASC\n"
      }
     ]
    },
    {
     "title": "Information",
     "type": "text",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
     "content": "\n# Queue Call Results\n\n1. Answered: the call is answered by an agent\n\n2. Abandoned: the caller hangs up while he is waiting for a free agent\n\n3. Unmanaged: the call is defined unmanaged when it doesn't enter to the queue or when it exits form a queue according to the queue settings (e.g. timeout, leave empty, join empy, exitwithkey, etc..)\n\n\n\n",
     "targets": [
      {
       "rawSql": "SELECT\n  createdAt AS \"time\",\n  id\nFROM analytics_custom_reports\nWHERE\n  $__timeFilter(createdAt)\nORDER BY createdAt"
      }
     ]
    },
    {
     "title": "Queue Attended",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "SELECT \n  now() as 'time_sec',\n\tqueue AS 'metric', \n\tCOUNT(queue) AS value \nFROM \n\treport_queue \nWHERE \n\tTYPE='inbound' \n\tAND queuecallercomplete=1\n\tand $__timeFilter(queuecallerjoinAt)\nGROUP BY \n\tmetric\nORDER BY\n\tmetric asc;\n"
      }
     ]
    },
    {
     "title": "Queue abandoned",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "SELECT \n  now() as 'time_sec',\n\tqueue AS 'metric', \n\tCOUNT(queue) AS value \nFROM \n\treport_queue \nWHERE \n\tTYPE='inbound' \n\tAND queuecallerabandon=1\n\tand $__timeFilter(queuecallerjoinAt)\nGROUP BY \n\tmetric\nORDER BY\n\tmetric asc;\n"
      }
     ]
    },
    {
     "title": "Queue unmanaged",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "SELECT \n  now() as 'time_sec',\n\tqueue AS 'metric', \n\tCOUNT(queue) AS value \nFROM \n\treport_queue \nWHERE \n\tTYPE='inbound' \n\tAND queuecallerexit=1\n\tand $__timeFilter(queuecallerjoinAt)\nGROUP BY \n\tmetric\nORDER BY\n\tmetric asc;\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Global Voice Queue Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Answer rate",
     "type": "singlestat",
     "description": "% of answered calls",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 2 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT \n  $__timeGroup(queuecallerjoinAt,'5m') as time,\n  SUM(IF(queuecallercomplete=1,1,0))/COUNT(*)*100 as value\nFROM motion2.report_queue\nWHERE $__timeFilter(queuecallerjoinAt) and type='inbound'\nGROUP BY $__timeGroup(queuecallerjoinAt,'5m')\nORDER BY $__timeGroup(queuecallerjoinAt,'5m') ASC\n"
      }
     ]
    },
    {
     "title": "Abandon rate",
     "type": "singlestat",
     "description": "% of abandoned calls",
     "gridPos": { "h": 6, "w": 3, "x": 3, "y": 2 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT \n  $__timeGroup(queuecallerjoinAt,'5m') as time,\n  SUM(IF(queuecallerabandon=1,1,0))/COUNT(*)*100 as value\nFROM motion2.report_queue\nWHERE $__timeFilter(queuecallerjoinAt) and type='inbound'\nGROUP BY $__timeGroup(queuecallerjoinAt,'5m')\nORDER BY $__timeGroup(queuecallerjoinAt,'5m') ASC\n"
      }
     ]
    },
    {
     "title": "Unmanaged rate",
     "type": "singlestat",
     "description": "% of unmanaged calls",
     "gridPos": { "h": 6, "w": 3, "x": 6, "y": 2 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT \n  $__timeGroup(queuecallerjoinAt,'5m') as time,\n  SUM(IF(queuecallerexit=1,1,0))/COUNT(*)*100 as value\nFROM motion2.report_queue\nWHERE $__timeFilter(queuecallerjoinAt)  and type='inbound'\nGROUP BY $__timeGroup(queuecallerjoinAt,'5m')\nORDER BY $__timeGroup(queuecallerjoinAt,'5m') ASC\n"
      }
     ]
    },
    {
     "title": "Total",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 6, "w": 6, "x": 9, "y": 2 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "SELECT\n  now() as 'time_sec',\n  SUM(CASE WHEN queuecallerabandon=1 THEN 1\n  WHEN queuecallerexit=1 THEN 1\n  WHEN queuecallercomplete=1 THEN 1\n   END) as value,\n   \n  CASE WHEN queuecallercomplete=1 THEN \"Attended\"\n  WHEN queuecallerabandon=1 THEN \"Abandoned\"\n  WHEN queuecallerexit=1 THEN \"Unmanaged\" END as metric\nFROM \n\treport_queue\nWHERE \n  TYPE='inbound'\n\tand $__timeFilter(queuecallerjoinAt)\nGROUP BY metric"
      }
     ]
    },
    {
     "title": "AVG Talking Time",
     "type": "farski-blendstat-panel",
     "gridPos": { "h": 2, "w": 4, "x": 15, "y": 2 },
     "format": "dthms",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT \n  $__timeGroup(queuecallerjoinAt,'5m') as time,\n  FLOOR(AVG(TIMEDIFF(queuecallercompleteAt,queuecallerleaveAt))) as value\nFROM motion2.report_queue\nWHERE $__timeFilter(queuecallerjoinAt) and queuecallercomplete=1 and type='inbound'\nGROUP BY $__timeGroup(queuecallerjoinAt,'5m')\nORDER BY $__timeGroup(queuecallerjoinAt,'5m') ASC\n"
      }
     ]
    },
    {
     "title": "Total Offered",
     "type": "farski-blendstat-panel",
     "gridPos": { "h": 2, "w": 5, "x": 19, "y": 2 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "rawSql": "SELECT \n  $__timeGroup(queuecallerjoinAt,'5m') as time,\n  count(id) as value\nFROM motion2.report_queue\nWHERE $__timeFilter(queuecallerjoinAt) and type='inbound'\nGROUP BY $__timeGroup(queuecallerjoinAt,'5m')\nORDER BY $__timeGroup(queuecallerjoinAt,'5m') ASC\n"
      }
     ]
    },
    {
     "title": "AVG Answer Time",
     "type": "farski-blendstat-panel",
     "gridPos": { "h": 2, "w": 4, "x": 15, "y": 4 },
     "format": "dthms",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT \n  $__timeGroup(queuecallerjoinAt,'5m') as time,\n  FLOOR(AVG(TIMEDIFF(queuecallerleaveAt,queuecallerjoinAt))) as value\nFROM motion2.report_queue\nWHERE $__timeFilter(queuecallerjoinAt) and queuecallercomplete=1 and type='inbound'\nGROUP BY $__timeGroup(queuecallerjoinAt,'5m')\nORDER BY $__timeGroup(queuecallerjoinAt,'5m') ASC\n"
      }
     ]
    },
    {
     "title": "Total Answered",
     "type": "farski-blendstat-panel",
     "gridPos": { "h": 2, "w": 5, "x": 19, "y": 4 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "rawSql": "SELECT \n  $__timeGroup(queuecallerjoinAt,'5m') as time,\n  count(id) as value\nFROM motion2.report_queue\nWHERE $__timeFilter(queuecallerjoinAt) AND queuecallercomplete=1 and type='inbound'\nGROUP BY $__timeGroup(queuecallerjoinAt,'5m')\nORDER BY $__timeGroup(queuecallerjoinAt,'5m') ASC\n"
      }
     ]
    },
    {
     "title": "AVG Abandon Time",
     "type": "farski-blendstat-panel",
     "gridPos": { "h": 2, "w": 4, "x": 15, "y": 6 },
     "format": "dthms",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT \n  $__timeGroup(queuecallerjoinAt,'5m') as time,\n  FLOOR(AVG(TIMEDIFF(queuecallerabandonAt,queuecallerjoinAt))) as value\nFROM motion2.report_queue\nWHERE $__timeFilter(queuecallerjoinAt) and queuecallerabandon=1 and type='inbound'\nGROUP BY $__timeGroup(queuecallerjoinAt,'5m')\nORDER BY $__timeGroup(queuecallerjoinAt,'5m') ASC\n"
      }
     ]
    },
    {
     "title": "Total Unanswered",
     "type": "farski-blendstat-panel",
     "gridPos": { "h": 2, "w": 5, "x": 19, "y": 6 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "rawSql": "SELECT \n  $__timeGroup(queuecallerjoinAt,'5m') as time,\n  count(id) as value\nFROM motion2.report_queue\nWHERE $__timeFilter(queuecallerjoinAt) AND queuecallercomplete=0 and type='inbound'\nGROUP BY $__timeGroup(queuecallerjoinAt,'5m')\nORDER BY $__timeGroup(queuecallerjoinAt,'5m') ASC\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Selected Voice Queue Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Answer rate",
     "type": "singlestat",
     "description": "% of answered calls",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 3 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT \n  $__timeGroup(queuecallerjoinAt,'5m') as time,\n  SUM(IF(queuecallercomplete=1,1,0))/COUNT(*)*100 as value\nFROM motion2.report_queue\nWHERE $__timeFilter(queuecallerjoinAt) and type='inbound' and queue='$queue'\nGROUP BY $__timeGroup(queuecallerjoinAt,'5m')\nORDER BY $__timeGroup(queuecallerjoinAt,'5m') ASC\n"
      }
     ]
    },
    {
     "title": "Abandon rate",
     "type": "singlestat",
     "description": "% of abandoned calls",
     "gridPos": { "h": 6, "w": 3, "x": 3, "y": 3 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT \n  $__timeGroup(queuecallerjoinAt,'5m') as time,\n  SUM(IF(queuecallerabandon=1,1,0))/COUNT(*)*100 as value\nFROM motion2.report_queue\nWHERE $__timeFilter(queuecallerjoinAt) and type='inbound' and queue='$queue'\nGROUP BY $__timeGroup(queuecallerjoinAt,'5m')\nORDER BY $__timeGroup(queuecallerjoinAt,'5m') ASC\n"
      }
     ]
    },
    {
     "title": "Unmanaged rate",
     "type": "singlestat",
     "description": "% of unmanaged calls",
     "gridPos": { "h": 6, "w": 3, "x": 6, "y": 3 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT \n  $__timeGroup(queuecallerjoinAt,'5m') as time,\n  SUM(IF(queuecallerexit=1,1,0))/COUNT(*)*100 as value\nFROM motion2.report_queue\nWHERE $__timeFilter(queuecallerjoinAt)  and type='inbound' and queue='$queue'\nGROUP BY $__timeGroup(queuecallerjoinAt,'5m')\nORDER BY $__timeGroup(queuecallerjoinAt,'5m') ASC\n"
      }
     ]
    },
    {
     "title": "Total",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 6, "w": 6, "x": 9, "y": 3 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "SELECT\n  now() as 'time_sec',\n  SUM(CASE WHEN queuecallerabandon=1 THEN 1\n  WHEN queuecallerexit=1 THEN 1\n  WHEN queuecallercomplete=1 THEN 1\n   END) as value,\n   \n  CASE WHEN queuecallercomplete=1 THEN \"Attended\"\n  WHEN queuecallerabandon=1 THEN \"Abandoned\"\n  WHEN queuecallerexit=1 THEN \"Unmanaged\" END as metric\nFROM \n\treport_queue\nWHERE \n  TYPE='inbound'\n\tand $__timeFilter(queuecallerjoinAt)\n\tand queue='$queue'\nGROUP BY metric"
      }
     ]
    },
    {
     "title": "AVG Talking Time",
     "type": "farski-blendstat-panel",
     "gridPos": { "h": 2, "w": 4, "x": 15, "y": 3 },
     "format": "dthms",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT \n  $__timeGroup(queuecallerjoinAt,'5m') as time,\n  FLOOR(AVG(TIMEDIFF(queuecallercompleteAt,queuecallerleaveAt))) as value\nFROM motion2.report_queue\nWHERE $__timeFilter(queuecallerjoinAt) and queuecallercomplete=1 and queue='$queue'\nGROUP BY $__timeGroup(queuecallerjoinAt,'5m')\nORDER BY $__timeGroup(queuecallerjoinAt,'5m') ASC\n"
      }
     ]
    },
    {
     "title": "Total Offered",
     "type": "farski-blendstat-panel",
     "gridPos": { "h": 2, "w": 5, "x": 19, "y": 3 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "rawSql": "SELECT \n  $__timeGroup(queuecallerjoinAt,'5m') as time,\n  count(id) as value\nFROM motion2.report_queue\nWHERE $__timeFilter(queuecallerjoinAt) and queue='$queue'\nGROUP BY $__timeGroup(queuecallerjoinAt,'5m')\nORDER BY $__timeGroup(queuecallerjoinAt,'5m') ASC\n"
      }
     ]
    },
    {
     "title": "AVG Answer Time",
     "type": "farski-blendstat-panel",
     "gridPos": { "h": 2, "w": 4, "x": 15, "y": 5 },
     "format": "dthms",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT \n  $__timeGroup(queuecallerjoinAt,'5m') as time,\n  FLOOR(AVG(TIMEDIFF(queuecallerleaveAt,queuecallerjoinAt))) as value\nFROM motion2.report_queue\nWHERE $__timeFilter(queuecallerjoinAt) and queuecallercomplete=1 and queue='$queue'\nGROUP BY $__timeGroup(queuecallerjoinAt,'5m')\nORDER BY $__timeGroup(queuecallerjoinAt,'5m') ASC\n"
      }
     ]
    },
    {
     "title": "Total Answered",
     "type": "farski-blendstat-panel",
     "gridPos": { "h": 2, "w": 5, "x": 19, "y": 5 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "rawSql": "SELECT \n  $__timeGroup(queuecallerjoinAt,'5m') as time,\n  count(id) as value\nFROM motion2.report_queue\nWHERE $__timeFilter(queuecallerjoinAt) AND queuecallercomplete=1 and type='inbound'\nGROUP BY $__timeGroup(queuecallerjoinAt,'5m')\nORDER BY $__timeGroup(queuecallerjoinAt,'5m') ASC\n"
      }
     ]
    },
    {
     "title": "AVG Abandon Time",
     "type": "farski-blendstat-panel",
     "gridPos": { "h": 2, "w": 4, "x": 15, "y": 7 },
     "format": "dthms",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT \n  $__timeGroup(queuecallerjoinAt,'5m') as time,\n  FLOOR(AVG(TIMEDIFF(queuecallerabandonAt,queuecallerjoinAt))) as value\nFROM motion2.report_queue\nWHERE $__timeFilter(queuecallerjoinAt) and queuecallerabandon=1 and queue='$queue'\nGROUP BY $__timeGroup(queuecallerjoinAt,'5m')\nORDER BY $__timeGroup(queuecallerjoinAt,'5m') ASC\n"
      }
     ]
    },
    {
     "title": "Total Unanswered",
     "type": "farski-blendstat-panel",
     "gridPos": { "h": 2, "w": 5, "x": 19, "y": 7 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "rawSql": "SELECT \n  $__timeGroup(queuecallerjoinAt,'5m') as time,\n  count(id) as value\nFROM motion2.report_queue\nWHERE $__timeFilter(queuecallerjoinAt) AND queuecallercomplete=0 and queue='$queue'\nGROUP BY $__timeGroup(queuecallerjoinAt,'5m')\nORDER BY $__timeGroup(queuecallerjoinAt,'5m') ASC\n"
      }
     ]
    }
   ]
  }
 ]
}