{
 "title": "xCally Warnings",
 "time": { "from": "now/d", "to": "now/d" },
 "panels": [
  { "title": "Campaign Warnings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Non DDI campaigns",
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  now() as 'time_sec',\n  Count(id) as 'value'\nFROM \n  voice_queues\nWHERE\n  TYPE='outbound' AND  (dialOriginateCallerIdNumber IS NULL OR dialOriginateCallerIdNumber = '')\n"
    }
   ]
  },
  {
   "title": "Campaigns without hoppers",
   "type": "table",
   "gridPos": { "h": 12, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT id AS 'Identifier', name as 'Campaign' FROM voice_queues WHERE id NOT IN\r\n\t(\r\n\t\tSELECT \r\n\t\t\tDISTINCT(voicequeueid) AS 'Campaign'\r\n\t\tFROM \r\n\t\t\tcm_hopper\r\n\t)\r\nAND TYPE='outbound';"
    }
   ]
  },
  {
   "title": "Recallme without agent",
   "type": "table",
   "gridPos": { "h": 12, "w": 4, "x": 8, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT \r\n\tCOUNT(a.voicequeueid) AS  total, b.name \r\nFROM \r\n\tcm_hopper a,\r\n\tvoice_queues b\r\nWHERE \r\n\ta.voicequeueid = b.id\r\n\tand recallme=1 AND userid IS NULL \r\nGROUP BY voicequeueid"
    }
   ]
  },
  {
   "title": "Campaigns without DDI associated",
   "type": "table",
   "gridPos": { "h": 12, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "select\n  id,name\nfrom\n  voice_queues\nwhere \n  type='outbound'\n  and (dialOriginateCallerIdNumber is null or dialOriginateCallerIdNumber = '')\n"
    }
   ]
  },
  {
   "title": "Campaigns without agents",
   "type": "table",
   "gridPos": { "h": 12, "w": 4, "x": 16, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  id as 'Identifier', name as 'Campaign' \r\nFROM \r\n  voice_queues \r\nWHERE \r\n  id NOT IN\r\n\t(\r\n\t\tSELECT \r\n\t\t\tDISTINCT(voicequeueid) AS 'Campaign'\r\n\t\tFROM \r\n\t\t\tuser_has_voice_queues\r\n\t)\r\nAND TYPE='outbound';"
    }
   ]
  },
  {
   "title": "Campaigns without record",
   "type": "table",
   "gridPos": { "h": 12, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  id as 'Identifier', name as 'Campaign' \r\nFROM \r\n  voice_queues \r\nWHERE \r\n  monitor_format = ''"
    }
   ]
  },
  {
   "title": "Campaigns without hoppers",
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT NOW() AS 'time_sec', COUNT(id) AS 'value' FROM voice_queues WHERE id NOT IN\r\n\t(\r\n\t\tSELECT \r\n\t\t\tDISTINCT(voicequeueid) AS 'Campaign'\r\n\t\tFROM \r\n\t\t\tcm_hopper\r\n\t)\r\nAND TYPE='outbound';"
    }
   ]
  },
  {
   "title": "Campaigns without agents",
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT NOW() AS 'time_sec', COUNT(id) AS 'value' FROM voice_queues WHERE id NOT IN\r\n\t(\r\n\t\tSELECT \r\n\t\t\tDISTINCT(voicequeueid) AS 'Campaign'\r\n\t\tFROM \r\n\t\t\tuser_has_voice_queues\r\n\t)\r\nAND TYPE='outbound';"
    }
   ]
  },
  {
   "title": "Campaigns without recording",
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select \n  now() as 'time_sec',\n  count(id) as 'value' \nfrom \n  voice_queues \nwhere \n  monitor_format='' and type='outbound'"
    }
   ]
  },
  {
   "title": "Lists Warnings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Lists without hoppers",
     "type": "farski-blendstat-panel",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\r\n  now() as 'time_sec',\r\n\tcount(id) as 'value'\r\nFROM \r\n\tcm_lists\r\nWHERE id NOT IN\r\n\t(\r\n\t\tSELECT \r\n\t\t\tDISTINCT(ListId)\r\n\t\tFROM \r\n\t\t\tcm_hopper\r\n\t)"
      }
     ]
    },
    {
     "title": "Lists without hoppers",
     "type": "table",
     "gridPos": { "h": 8, "w": 6, "x": 4, "y": 2 },
     "targets": [
      {
       "rawSql": "SELECT \r\n\tid,name\r\nFROM \r\n\tcm_lists\r\nWHERE id NOT IN\r\n\t(\r\n\t\tSELECT \r\n\t\t\tDISTINCT(ListId)\r\n\t\tFROM \r\n\t\t\tcm_hopper\r\n\t)"
      }
     ]
    },
    {
     "title": "Lists without agents",
     "type": "table",
     "gridPos": { "h": 8, "w": 6, "x": 10, "y": 2 },
     "targets": [
      {
       "rawSql": "SELECT \r\n\tid as 'Identifier',\r\n\tname as 'List'\r\nFROM \r\n\tcm_lists\r\nWHERE id NOT IN\r\n\t(\r\n\t\tSELECT \r\n\t\t\tDISTINCT(CmListId)\r\n\t\tFROM \r\n\t\t\tcm_user_has_lists\r\n\t)"
      }
     ]
    },
    {
     "title": "Lists without agents",
     "type": "farski-blendstat-panel",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT \r\n\tNOW() AS 'time_sec',\r\n\tcount(id) AS 'value' \r\nFROM \r\n\tcm_lists\r\nWHERE id NOT IN\r\n\t(\r\n\t\tSELECT \r\n\t\t\tDISTINCT(CmListId)\r\n\t\tFROM \r\n\t\t\tcm_user_has_lists\r\n\t)"
      }
     ]
    }
   ]
  },
  {
   "title": "Agents Warnings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Agents without campaigns",
     "type": "farski-blendstat-panel",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT \r\n\tNOW() AS 'time_sec',\r\n\tcount(id) AS 'value' \r\nFROM \r\n\tusers\r\nWHERE id NOT IN\r\n\t(\r\n\t\tSELECT \r\n\t\t\tDISTINCT(userid)\r\n\t\tFROM \r\n\t\t\tuser_has_voice_queues\r\n\t)\r\nand role='agent'"
      }
     ]
    },
    {
     "title": "Agents without campaigns",
     "type": "table-old",
     "gridPos": { "h": 9, "w": 5, "x": 4, "y": 3 },
     "targets": [
      {
       "rawSql": "SELECT \r\n\tid,name\r\nFROM \r\n\tusers\r\nWHERE id NOT IN\r\n\t(\r\n\t\tSELECT \r\n\t\t\tDISTINCT(userid)\r\n\t\tFROM \r\n\t\t\tuser_has_voice_queues\r\n\t)\r\nand role='agent'"
      }
     ]
    },
    {
     "title": "Agents without lists",
     "type": "table-old",
     "gridPos": { "h": 9, "w": 5, "x": 9, "y": 3 },
     "targets": [
      {
       "rawSql": "SELECT \r\n\tid AS 'Identifier',\r\n\tname as 'Agent'\r\nFROM \r\n\tusers\r\nWHERE id NOT IN\r\n\t(\r\n\t\tSELECT \r\n\t\t\tDISTINCT(UserId)\r\n\t\tFROM \r\n\t\t\tcm_user_has_lists\r\n\t)\r\nAND role='agent'\r\n\r\n"
      }
     ]
    },
    {
     "title": "Agents without lists",
     "type": "table-old",
     "gridPos": { "h": 9, "w": 6, "x": 14, "y": 3 },
     "targets": [
      {
       "rawSql": "SELECT \r\n  id,\r\n\tname,\r\n\tfullname\r\nFROM \r\n\tusers\r\nWHERE \r\nloginInPause='0'\r\nAND role='agent'"
      }
     ]
    },
    {
     "title": "Agents without lists",
     "type": "farski-blendstat-panel",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT \r\n\tNOW() AS 'time_sec',\r\n\tcount(id) AS 'value' \r\nFROM \r\n\tusers\r\nWHERE id NOT IN\r\n\t(\r\n\t\tSELECT \r\n\t\t\tDISTINCT(UserId)\r\n\t\tFROM \r\n\t\t\tcm_user_has_lists\r\n\t)\r\nAND role='agent'\r\n\r\n"
      }
     ]
    },
    {
     "title": "Agents without Login In Pause",
     "type": "farski-blendstat-panel",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT \r\n\tNOW() AS 'time_sec',\r\n\tcount(id) AS 'value' \r\nFROM \r\n\tusers\r\nWHERE \r\nloginInPause='0'\r\nAND role='agent'\r\n\r\n"
      }
     ]
    }
   ]
  }
 ]
}