{
 "title": "xCally Manual Calls",
 "time": { "from": "now/d", "to": "now/d" },
 "templating": {
  "list": [
   {
    "name": "agent",
    "label": "Agent",
    "query": "select internal as __value, name as __text from users where role='agent';"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Calls",
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time_sec,\n  count(id) as value\nFROM \n  report_call\nWHERE\n  type='outbound'\n  and $__timeFilter(starttime)\n"
    }
   ]
  },
  {
   "title": "Anwered Calls",
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time_sec,\n  count(id) as value\nFROM \n  report_call\nWHERE\n  type='outbound'\n  and disposition='ANSWERED'\n  and $__timeFilter(starttime)\n"
    }
   ]
  },
  {
   "title": "Manual Calls Dispositions",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 7, "x": 9, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  now() AS \"time_sec\",\n  count(userDisposition) as \"value\",\n  userDisposition as \"metric\"\nFROM \n  report_call\nWHERE\n  type='outbound'\n  and $__timeFilter(starttime)\ngroup by metric"
    }
   ]
  },
  {
   "title": "Call per Agent",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT \n\tb.name,\n\tCOUNT(a.accountcode) AS \"value\"\nFROM \n\treport_call a, users b\nWHERE \n\ta.accountcode = b.internal\n\tand a.type='outbound'\n\tAND $__timeFilter(starttime)\nGROUP BY b.name\nORDER BY b.name asc\n"
    }
   ]
  },
  {
   "title": "Disposed Calls",
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time_sec,\n  count(id) as value\nFROM \n  report_call\nWHERE\n  type='outbound'\n  and userDisposition is not null\n  and $__timeFilter(starttime)\n"
    }
   ]
  },
  {
   "title": "Unanswered Calls",
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time_sec,\n  count(id) as value\nFROM \n  report_call\nWHERE\n  type='outbound'\n  and disposition='NO ANSWER'\n  and $__timeFilter(starttime)\n"
    }
   ]
  },
  {
   "title": "Not Disposed Calls",
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time_sec,\n  count(id) as value\nFROM \n  report_call\nWHERE\n  type='outbound'\n  and userDisposition is null\n  and $__timeFilter(starttime)\n"
    }
   ]
  },
  {
   "title": "Total Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  now() AS \"time_sec\",\n  sum(billableseconds) as duration\nFROM \n  report_call\nWHERE\n  type='outbound'\n  and $__timeFilter(starttime)\n"
    }
   ]
  },
  { "title": "Agent Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Agent Dispositions",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 11 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  now() AS 'time_sec',\n  count(userDisposition) as 'value',\n  userDisposition as 'metric'\nFROM \n  report_call\nWHERE\n  accountcode='$agent'\n  and type='outbound'\n  and $__timeFilter(createdAt)\ngroup by metric"
    }
   ]
  },
  {
   "title": "State Calls",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 11 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  now() AS \"time\",\n  count(disposition) as 'value',\n  disposition as 'metric'\nFROM \n  report_call\nWHERE\n  $__timeFilter(createdAt)\nGROUP by\n  metric"
    }
   ]
  },
  {
   "title": "Disposed Calls",
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time_sec,\n  count(id) as value\nFROM \n  report_call\nWHERE\n  type='outbound'\n  and accountcode='$agent'\n  and userDisposition is not null\n  and $__timeFilter(starttime)\n"
    }
   ]
  },
  {
   "title": "Not Disposed Calls",
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time_sec,\n  count(id) as value\nFROM \n  report_call\nWHERE\n  type='outbound'\n  and userDisposition is null\n  and accountcode='$agent'\n  and $__timeFilter(starttime)\n"
    }
   ]
  }
 ]
}