{
 "title": "xCally Campaign Sales",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Sales & Pre-Sales (Hopper Final)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pre-sales",
     "type": "farski-blendstat-panel",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "rawSql": "SELECT \n  $__timeGroup(starttime,'1h') as 'time_sec',\n  COUNT(disposition) as 'value'\nFROM \n  cm_hopper_final\nWHERE \n    $__timeFilter(starttime) \n  and \n    disposition = 'Pre-venta'\nGROUP BY \n  $__timeGroup(starttime,'1h')\nORDER BY \n$__timeGroup(starttime,'1h') ASC"
      }
     ]
    },
    {
     "title": "Sales & Pre-sales by hour",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 3, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT \n  $__timeGroup(starttime,'1h') as time,\n  count(disposition) as value,\n  disposition as metric\nFROM \n  cm_hopper_final\nWHERE \n    $__timeFilter(starttime) \n  and \n    disposition like '%venta'\nGROUP BY \n  metric, $__timeGroup(starttime,'1h')\nORDER BY \n$__timeGroup(starttime,'1h') ASC"
      }
     ]
    },
    {
     "title": "Sales & pre-sales per campaign",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 11, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT \n  $__timeGroup(starttime,'1h') as time,\n  count(campaign) as value,\n  campaign as metric\nFROM \n  cm_hopper_final\nWHERE \n    $__timeFilter(starttime) \n  and \n    disposition like '%venta'\nGROUP BY \n  metric, $__timeGroup(starttime,'1h')\nORDER BY \n$__timeGroup(starttime,'1h') ASC"
      }
     ]
    },
    {
     "title": "Sales & Pre-sales per campaign",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
     "format": "short",
     "valueName": "total",
     "targets": [
      {
       "rawSql": "SELECT \n  $__timeGroup(starttime,'1h') as time,\n  count(campaign) as value,\n  campaign as metric\nFROM \n  cm_hopper_final\nWHERE \n    $__timeFilter(starttime) \n  and \n    disposition like '%venta'\nGROUP BY \n  metric, $__timeGroup(starttime,'1h')\nORDER BY \n$__timeGroup(starttime,'1h') ASC"
      }
     ]
    },
    {
     "title": "Sales",
     "type": "farski-blendstat-panel",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "rawSql": "SELECT \n  $__timeGroup(starttime,'1h') as 'time_sec',\n  COUNT(disposition) as 'value'\nFROM \n  cm_hopper_final\nWHERE \n    $__timeFilter(starttime) \n  and \n    disposition = 'venta'\nGROUP BY \n  $__timeGroup(starttime,'1h')\nORDER BY \n$__timeGroup(starttime,'1h') ASC"
      }
     ]
    },
    {
     "title": "Sales per campaign ",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT \n  $__timeGroup(starttime,'1h') as time,\n  count(campaign) as value,\n  campaign as metric\nFROM \n  cm_hopper_final\nWHERE \n    $__timeFilter(starttime) \n  and \n    disposition = 'venta'\nGROUP BY \n  metric, $__timeGroup(starttime,'1h')\nORDER BY \n$__timeGroup(starttime,'1h') ASC"
      }
     ]
    },
    {
     "title": "Sales per campaign",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 8 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "SELECT \n  now() as 'time_sec',\n  count(campaign) as value,\n  campaign as metric\nFROM \n  cm_hopper_final\nWHERE \n    $__timeFilter(starttime) \n  and \n    disposition = 'venta'\nGROUP BY \n  metric\n"
      }
     ]
    },
    {
     "title": "Pre-Sales per campaign",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT \n  $__timeGroup(starttime,'1h') as time,\n  count(campaign) as value,\n  campaign as metric\nFROM \n  cm_hopper_final\nWHERE \n    $__timeFilter(starttime) \n  and \n    disposition = 'Pre-venta'\nGROUP BY \n  metric, $__timeGroup(starttime,'1h')\nORDER BY \n$__timeGroup(starttime,'1h') ASC"
      }
     ]
    },
    {
     "title": "Pre-Sales per campaign",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 8 },
     "format": "short",
     "valueName": "total",
     "targets": [
      {
       "rawSql": "SELECT \n  now() as 'time_sec',\n  count(campaign) as value,\n  campaign as metric\nFROM \n  cm_hopper_final\nWHERE \n    $__timeFilter(starttime) \n  and \n    disposition = 'Pre-venta'\nGROUP BY \n  metric\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Sales & Pre-Sales (Report Call)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pre-Sales",
     "type": "farski-blendstat-panel",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT \n  now() as time_sec,\n  count(userdisposition) as total\nFROM \n  report_call\nWHERE \n    $__timeFilter(starttime) \n  and \n    userdisposition = 'Pre-venta'\nGROUP BY \n  userdisposition\n"
      }
     ]
    },
    {
     "title": "Sales & Pre-Sales by Call Direction",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 4, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT \n  $__timeGroup(starttime,'1h') as time,\n  count(type) as value,\n  type as metric\nFROM \n  report_call\nWHERE \n    $__timeFilter(starttime) \n  and \n    userdisposition like '%venta'\nGROUP BY \n  metric, $__timeGroup(starttime,'1h')\nORDER BY \n$__timeGroup(starttime,'1h') ASC"
      }
     ]
    },
    {
     "title": "Sales & Pre-Sales by Hour",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 11, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT \n  $__timeGroup(starttime,'1h') as time,\n  count(userdisposition) as value,\n  userdisposition as metric\nFROM \n  report_call\nWHERE \n    $__timeFilter(starttime) \n  and \n    userdisposition like '%venta'\nGROUP BY \n  metric, $__timeGroup(starttime,'1h')\nORDER BY \n$__timeGroup(starttime,'1h') ASC"
      }
     ]
    },
    {
     "title": "Sales & Pre-Sales by Call Direction",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 2 },
     "format": "short",
     "valueName": "total",
     "targets": [
      {
       "rawSql": "SELECT \n  $__timeGroup(starttime,'1h') as time,\n  count(type) as value,\n  type as metric\nFROM \n  report_call\nWHERE \n    $__timeFilter(starttime) \n  and \n    userdisposition like '%venta'\nGROUP BY \n  metric, $__timeGroup(starttime,'1h')\nORDER BY \n$__timeGroup(starttime,'1h') ASC"
      }
     ]
    },
    {
     "title": "Sales",
     "type": "farski-blendstat-panel",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT \n  now() as time_sec,\n  count(userdisposition) as total\nFROM \n  report_call\nWHERE \n    $__timeFilter(starttime) \n  and \n    userdisposition = 'venta'\nGROUP BY \n  userdisposition\n"
      }
     ]
    }
   ]
  }
 ]
}