{
 "title": "xCally Contacts",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Contact Lists",
   "type": "table",
   "gridPos": { "h": 19, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n  b.id,b.name,b.description,COUNT(a.id) AS 'contacts' \nFROM \n  cm_contacts a,cm_lists b \nWHERE a.listid=b.id \nGROUP BY a.listid"
    }
   ]
  },
  {
   "title": "Total lists",
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select now() as time_sec, count(id) as value from cm_lists;"
    }
   ]
  },
  {
   "title": "Duplicate phones by list",
   "type": "table",
   "gridPos": { "h": 19, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    phone,\r\n    COUNT(phone),\r\n    firstName,\r\n    listId\r\nFROM\r\n    cm_contacts\r\nGROUP BY phone,firstName,listid\r\nHAVING COUNT(phone) > 1\r\nORDER BY COUNT(phone) DESC;"
    }
   ]
  }
 ]
}